export default [
 {
  name: 'Chapter 1. The carrots are gone',
  description: `After a long nice sleep you've waken up to a nice sunrise, but what's that noice? 
  It's your stomach.."Time to eat!", you run to your house, you open the door.. no carrots. Someone
  must have taken them. Lets chase them..`,
  movie:'movie.mp4',
  layout:[
   "                                                                  ",
   "                                                                  ",
   "                                                                  ",
   "        lxxr                                                      ",
   "                                                                  ",
   "                                                                  ",
   "                                                                  ",
   "                                                                  ",
   "                                                                  ",
   "                                                                  ",
   "                                lxxr                              ",
   "                                                                  ",
   "                                                                  ",
   "                                      lxxr                        ",
   "                                                                  ",
   "                                                                  ",
   "                         c                                        ",
   "                       lxxr                                       ",
   "                                     cc                           ",
   "             c   lxxr         lxxxxxxxxr                          ",
   "xxr         p                                                     ",
   "  i        lxxr            lxr                                    ",
   "  i                     lr                                        ",
   "  i                  lr                                           ",
   "  i          lx    xr                                              ",
   "  i  @       i     i                   p  p p pppp    p p p p     ",
   "  xxxxxxxxxxxr     lxxxxxxxxxxr   lxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxr",
   "                                                                  ",
   "                                                                  "]
 },
 {
  name: 'Chapter 2. The jump is real',
  description: `.. he's quick.. too quick for you. The fox has taken the higher ground, there is only one way up,
  make good use of the jumpers to catch that fox.`,
  movie:'movie.mp4',
  layout:
  ["                                         ",
   "                                         ",
   "                                         ",
   "                                         ",
   "                                         ",
   "                       c                 ",
   "r                    lxr                 ",
   "i                            p           ",
   "i                      p   lxxxr         ",
   "i                 c  lxxxr               ",
   "i          p    lxxr                     ",
   "i        lxxxr                           ",
   "i @                    p                 ",
   "xxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                         ",
   "                                         ",
   "                                         "]
 }
]