export default [
       ["                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "        lxxr                                                      ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                                                  ",
        "                                lxxr                              ",
        "                                                                  ",
        "                                                                  ",
        "                                      lxxr                        ",
        "                                                                  ",
        "                                                                  ",
        "                         c                                        ",
        "                       lxxr                                       ",
        "                                     cc                           ",
        "             c   lxxr         lxxxxxxxxr                          ",
        "xxr         p                                                     ",
        "  i        lxxr            lxr                                    ",
        "  i                     lr                                        ",
        "  i                  lr                                           ",
        "  i          lxxxxxr                                              ",
        "  i  @       i     i                   p  p p pppp    p p p p     ",
        "  xxxxxxxxxxxr     lxxxxxxxxxxr   lxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxr",
        "                                                                  ",
        "                                                                  "],

       ["                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                                         ",
        "                       c                 ",
        "r                    lxr                 ",
        "i                            p           ",
        "i                      p   lxxxr         ",
        "i                 c  lxxxr               ",
        "i          p    lxxr                     ",
        "i        lxxxr                           ",
        "i    @                 p                 ",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "                                         ",
        "                                         ",
        "                                         "],

];