export default [
       ["                                                                  ",
        "                                                                  ",
        "                                     cc                           ",
        "             c                c    xxxxx                          ",
        "            p                xxxx                                 ",
        "  x        xxxx             x                                     ",
        "  x                    x                                          ",
        "  x                  x                                            ",
        "  x          xxxxxxx                                              ",
        "  x  @       x  x                      p  p p pppp    p p p p     ",
        "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "                                                                  ",
        "                                                                  ",
        "                                                                  "],

       ["                                         ",
        "                                         ",
        "                       c                 ",
        "                     xxx                 ",
        "                                         ",
        "                           xxxxx         ",
        "                  c  xxxxx               ",
        "           p    xxxx                     ",
        "         xxxxx                           ",
        "     @                                   ",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "                                         ",
        "                                         ",
        "                                         "],

];